### ISSUE TITLE
new hbl channel.

### ISSUE THREAD

**Issue by CrafterPika** [hacks-guide/Guide-WiiU#1]
this modified channel by GaryOderNichts fixes the .elf loading issue, could it be used for the guide?
Channel:
https://github.com/GaryOderNichts/homebrew_launcher/releases

**Comment by Elpunical** [comment]
The fix is going to be merged into the main repo, therefore, the links in the guide won't be changed.

**Comment by Elpunical** [comment]
Fixed in f88f67a3501670544694b38567f5cea9874e18eb
