### ISSUE TITLE
The cIOS slots in vWii Modding guide could be updated

### ISSUE THREAD

**Issue by MatthewL246** [hacks-guide/Guide-WiiU#112]
Guide section: https://wiiu.hacks.guide/#/vwii-modding?id=installing-cioses
See https://wiki.gbatemp.net/wiki/Wii_cIOS_base_Compatibility_List. The important part:

> You can only use one IOS at a time, so the only reason we ever cared to install different cIOSs to alternate slots was to be able to quickly switch between them when for some reason your primary 249 didn't work with a particular game or homebrew. cIOSs have evolved to a point where 1 cIOS is compatible 99% of the time, that cIOS is called d2x with base 57 (which for the Wii is the equivalent of d2x v10 beta 52. NOT beta 53!)
>
> Previously it was recommended to use base 56 as the default installed to slot 249, even though base 57 offered better compatibility than base 56, as it was believed to offer slightly faster loading speeds, which eventually was never proven to be true. So until recently (2018-2019) this is what was usually recommended to install to slots 249 and 250:
>
> slot 249: base 56
> slot 250: base 57
>
> As a lot of new gamers struggled to fix "Call of Duty" because they didn't know to just use a different cIOS slot that uses base 57 by selecting slot 250 it in their loader's game options, and considering most games working with 56 also work with 57 (we're really comparing 97%-98% compatibility with 99%!!), many softmod guides recently (2018-2020) changed the default base in slot 249 to 57 so the recommendation changed to this:
>
> slot 249: base 57
> slot 250: base 56

Currently, the guide says to install base 56 to slot 249 and base 57 to slot 250, like the mentioned "older guides." Unless there is a reason specific to the Wii U vWii that I am missing, it seems like it would be better to suggest installing base 57 to slot 249, base 56 to slot 250, and base 58 to slot 251 (side note: it looks like patching base 58 is unnecessary according to newer guides, but it also looks like there is no harm in doing so.)

*Edit: Maybe you should also add a link to the cIOS compatibility list in a note box? Or maybe that would go against the main theme of the guide, which is to be as simple as possible.*

**Comment by GaryOderNichts** [comment]
This seems to be related to https://github.com/hacks-guide/Guide-WiiU/pull/82.
> Maybe you should also add a link to the cIOS compatibility list in a note box?

This might be a possible solution for this. I'm not sure if that's worth it though, switching the cIOS in the loader is a really simple step.

**Comment by MatthewL246** [comment]
I see, yeah this is basically a duplicate of #82. However, I believe that this change is worth looking into because it is such a minor change that will provide a slightly better default for people who are new to vWii homebrew.

On the other hand, I understand that this change might also confuse those people when they try to ask for help when something is not working in their USB loaders.

**Comment by Lazr1026** [comment]
The vWii guide is using v11 (which I think adds more compatibility? not a vWii person) so I do not think this is relevant anymore.
Also been 2 years since any activity.
