### ISSUE TITLE
Add d2x-cios-installer hang to known issues

### ISSUE THREAD

**Issue by henryptung** [hacks-guide/Guide-WiiU#116]
d2x-cios-installer can hang when loading from Homebrew Channel (at 3% or 6%). In my experience, this is due to SD cards formatted with MBR; formatting the SD card as a single FAT volume (with no partitions) resolved it for me.

**Comment by GaryOderNichts** [comment]
The Wii U only accepts SD Cards formatted as MBR with a single FAT32 volume anyways, which is also what the guide recommends.
This shouldn't be an issue if your SD is set up properly.
