### ISSUE TITLE
Add "Next Steps" section to the guides

### ISSUE THREAD

**Issue by MatthewL246** [hacks-guide/Guide-WiiU#118]
One thing that I think is lacking in the guides is some suggestions for what to do after installing CFW. I feel like the guide ends too abruptly after booting into CFW.

I suggest adding another section after the "booting into CFW" section with a few helpful next steps for some of the most popular things to do with homebrew. Also, note that most of these things can be links to existing guides, so they do not need to be written from scratch.

**Here are my suggestions:**
For the Wii U guide:

- A link to browse the [Homebrew App Store](https://apps.fortheusers.org/wiiu) and find new programs
- Installing game mods/romhacks
- A guide for installing (or just a link to) [RetroArch](https://apps.fortheusers.org/wiiu/retroarch)
- Creating Home Menu forwarders to homebrew programs
- Backing up and restoring game saves with SaveMii
- Dumping game disks with disc2app and installing with WUP Installer GX2 (already in the guide)
- Setting up Bloopair
- Recommendations for buying and setting up an external HDD
- At some point after it releases hopefully, a guide for using the [Pretendo Network](https://pretendo.network)
- Maybe a link to the 3DS guide, since it's the same website after all

For the vWii guide:

- Installing the [Open Shop Channel](https://oscwii.org/)
- Installing Nintendont (including vWii menu and/or Wii U menu forwarders)
- Link to the [RiiConnect24 tutorial](https://wii.guide/riiconnect24-vwii)
- Link to the [WiiLink24 tutorial](https://wii.guide/wiilink.html)
- Link to the [Wiimmfi tutorial](https://wii.guide/wiimmfi) (with Priiloader brick warning)
- Some more Wii Menu homebrew forwarders
- Maybe [this guide](https://gbatemp.net/threads/the-definitive-vwii-hacking-guide.425852/), not sure if it's outdated
- Possibly something else from the wii.guide "What can I do with homebrew?" section
- Maybe the guide for [installing vWii themes](https://demo.hedgedoc.org/s/2mYWv0YvK#), but it has a brick risk

Please let me know if you have more suggestions so I can update the list.

**Comment by takoyaki99** [comment]
I think Bloopair would be smart.
Maybe an HDD section would be nice as well!

**Comment by MatthewL246** [comment]
Thanks for the suggestions. I added them to the list.

Another thing that I should mention is that I would be willing to create a pull request for some of these things.

**Comment by takoyaki99** [comment]
I’ll get to work on some stuff that I can help with for a pull request!

**Comment by MatthewL246** [comment]
Looks like commit bc62317c28d4814c18e2a02a781496a753baf9b0 is already working on this.

**Comment by Lazr1026** [comment]
Finalizing Setup does some of this and the hacks.guide wiki does contain some of the things listed here.
Also over a year since the last activity.

**Comment by MatthewL246** [comment]
Seems good to me 👍
