### ISSUE TITLE
Add guide for installing Aroma

### ISSUE THREAD

**Issue by hifinerd** [hacks-guide/Guide-WiiU#144]
Since Aroma finally got a public beta, I believe an installation guide should be added, because Aroma adds many, _many_ useful features to the Wii U. 
Given that it is still a public beta, I personally think it should not be a part of the main guide just yet, and should be peppered with CYA warnings to let users know that while this is an option you can take, it's not wise to do so just yet.

**Comment by GaryOderNichts** [comment]
We were planning to wait for a stable release before recommending it in the guide.
Things that are "not wise to do so just yet" should not be on the guide just yet.

**Comment by Luca06Luwa** [comment]
Would the aroma guide be similar to how the haxchi and CBHC guides were. I mean like would it still have the tiramisu guide and have the aroma guide as a seperate option.

**Comment by Lazr1026** [comment]
Whenever Aroma has a stable release I would imagine we would switch the guide to have aroma only.

**Comment by Luca06Luwa** [comment]
I have created the pull request #153 where the aroma guide is in the works.

**Comment by GaryOderNichts** [comment]
An initial Aroma guide has been added as an optional step at the end of the Tiramisu guide.
