### ISSUE TITLE
Consider which "Blocking Updates" method is easier

### ISSUE THREAD

**Issue by JohnVeness** [hacks-guide/Guide-WiiU#155]
Currently https://wiiu.hacks.guide/#/block-updates lists two methods. The DNS method is described as easier, but the way it is written looks more complicated than the Delete Update Folder method!

Unless I'm missing some advantage of the DNS method, I think only the Delete Update Folder method should be shown on this page.

**Comment by Luca06Luwa** [comment]
Deleting the update folder does seem to be the recommended way of update blocking as UFDiine is a really simple program to use. So maybe saying that Deleting Update Folder is recommended wouldn't be a bad idea.

**Comment by Luca06Luwa** [comment]
Did some modifications to the update blocking page in the aroma guide PR. Basically made it so UFDiine is the recommended way now.

**Comment by GaryOderNichts** [comment]
You don't need access to homebrew for the DNS method and it also does not modify system files.
I think it's fine to keep both methods listed? Maybe it could be explained a bit more detailed.

**Comment by JohnVeness** [comment]
I guess the problem is the DNS method tab includes instructions for nnupatcher too, making it longer.

**Comment by Lazr1026** [comment]
Deleting the update folder is the easiest option as UFDiine is very easy to use.
Closing it now as the last activity was over a year ago.
