### ISSUE TITLE
Should specify which SD cards can be used

### ISSUE THREAD

**Issue by Vitani** [hacks-guide/Guide-WiiU#160]
Currently [the guide](https://wiiu.hacks.guide/#/introduction?id=before-starting) says "A 32GB SD Card will be enough for most use-cases.", but the Wii U does not support ~~cards any bigger than this, nor does it support~~ SDXC cards ([source](https://en-americas-support.nintendo.com/app/answers/detail/a_id/1263/~/what-sd-cards-are-compatible%3F)).

It would be good to know these limitations before starting the process.

**Comment by lifehackerhansol** [comment]
_Nintendo_ says this because this is the official FAT32 limitation.

The _actual_ limitation is somewhere at 2TB.

But yes, a note about this should be added.

**Comment by Lazr1026** [comment]
I'm using a 64GB SD Card fine, on multiple (wiiu) consoles. It sounds like your adapter or card has issues.

**Comment by Vitani** [comment]
> I'm using a 64GB SD Card fine, on multiple (wiiu) consoles. It sounds like your adapter or card has issues.

Did you use an SDXC or SDHC card?

**Comment by Lazr1026** [comment]
SDXC

**Comment by lifehackerhansol** [comment]
64GB and above are SDXC. You can't have an SDHC 64GB card.

**Comment by Vitani** [comment]
I just tried a different adapter (and gave the SD card slot a little old-school cleaning), and successfully saved a Mii photo to the SD card, so the Wii U can certainly write to it. I'll re-try the process now.

**Comment by Vitani** [comment]
That worked, thanks for your support peeps!
