### ISSUE TITLE
Update vWii modding cIOS guide to v11

### ISSUE THREAD

**Issue by scootyrooty** [hacks-guide/Guide-WiiU#170]
Can the [vWii Modding Guide](https://wiiu.hacks.guide/#/vwii-modding) please be updated to use the new d2x-cios v11 beta1

You can find the link to the cIOS and recommended config for vWii here: [https://github.com/wiidev/usbloadergx#cios-guide](https://github.com/wiidev/usbloadergx#cios-guide)

**Comment by Luca06Luwa** [comment]
I have created #172 which updates the version of the cIOS.
