### ISSUE TITLE
Instructions about uninstalling a legacy CFW setup don't mention RedNAND

### ISSUE THREAD

**Issue by arromdee** [hacks-guide/Guide-WiiU#173]
They should mention it, and explain how to export your tickets for anything installed on USB.  Don't tell people to uninstall Haxchi before using it to get into RedNAND and export their tickets.

**Comment by Lazr1026** [comment]
The average person doesnt have a redNAND and if they do they can load the Homebrew Launcher Installer payload and then load Mocha from the homebrew launcher. I dont see a need to add this to the guide.

**Comment by Lazr1026** [comment]
I am closing this because I have not seen anyone with a legacy redNAND in a long time, and that minutes redNAND completely replaced it
