### ISSUE TITLE
Dumping Wii Discs doesn't contain command for Powershell

### ISSUE THREAD

**Issue by Avenred** [hacks-guide/Guide-WiiU#175]
On this page: https://wiiu.hacks.guide/#/dump-wii-games it shows instructions on how to join the two .iso files together using CMD, but doesn't show how to do so with Powershell. Powershell is shown by default when right clicking inside of a folder on Windows 10 and 11, so it'd be nice to have the PS command there as well.
From a bit of googling, `Get-Content *.part?.iso | Set-Content game.iso` seems to do the trick.

**Comment by MechanicalDragon0687** [comment]
powershell is generally not the default. it must be switched in taskbar settings to open powershell instead of command prompt

that said, both should probably be given (though powershell should accept command prompt commands)

**Comment by Avenred** [comment]
On Win 11, the terminal app (which is now installed by default) opens up Powershell by default. "Open in Terminal" appears when shift right clicking in a folder too. Not sure about Win 10 since I haven't used it in a while, but I think it shows "Open in Powershell" as the default when shift right clicking.

There's also [this](https://support.microsoft.com/en-us/windows/powershell-is-replacing-command-prompt-fdb690cf-876c-d866-2124-21b6fb29a45f) which seems to indicate that Powershell is the default

**Comment by Lazr1026** [comment]
Seems to no longer be needed with #181 being merged
