### ISSUE TITLE
Sigpatch file not included in Aroma instructions

### ISSUE THREAD

**Issue by The-Randalorian** [hacks-guide/Guide-WiiU#179]
In order to load some games installed to the USB, the file 01_sigpatches.rpx is needed in the environment. The instructions for Tiramisu include a link to download the file and instructions on where to place it. The Aroma instructions do not include this step.

**Comment by bw118** [comment]
Same here... ;-)

**Comment by Lazr1026** [comment]
Closing this as the only legitimate use for signature patches on Aroma are VC injects, and it has been added to the UWUVCI guide.
