### ISSUE TITLE
Switch over to Compat Title Installer fork

### ISSUE THREAD

**Issue by Xpl0itU** [hacks-guide/Guide-WiiU#182]
It’s now been put on the hbas and the old version marked as legacy, I don’t see any reason as to why not use the fork, which works with aroma too, so users don’t have to switch to tiramisu just to mod their wii u
[https://apps.fortheusers.org/wiiu/CompatTitleInstaller](https://apps.fortheusers.org/wiiu/CompatTitleInstaller)

**Comment by VannyBuns** [comment]
#197 Will have this change. Should've done that from my previous PRs

**Comment by Lazr1026** [comment]
Guide uses your WUT port, closing this.
