### ISSUE TITLE
Remove brick warnings relating to installing Priiloader on the vWii

### ISSUE THREAD

**Issue by swaggio7** [hacks-guide/Guide-WiiU#186]
Priiloader now has vWii support and is now (kinda) safe to install on the Wii U. More can be seen here: https://github.com/DacoTaco/priiloader/discussions/339

**Comment by Lazr1026** [comment]
This can be closed due to [this](https://github.com/hacks-guide/Guide-WiiU/commit/2240c81eed8dc27a019f4fd69b626cbcd76482a1)
