### ISSUE TITLE
drc-sim guide

### ISSUE THREAD

**Issue by upintheairsheep** [hacks-guide/Guide-WiiU#218]
If the Wii U Gamepad and/or the Wii U Gamepad Charger is damaged, lost, stolen, never came with the Wii U, disposed in trash, sold, recycled, or given away, a tool, https://github.com/rolandoislas/drc-sim is able to emulate a Wii U gamepad to help homebrew the Wii U without a GamePad or GamePad charger, even without Wii remotes or Pro Controllers. I personally have a Wii U gamepad charger that failed, my second one to fail that same way.

**Comment by Lazr1026** [comment]
i am absolutely not going to maintain a drc-sim guide. it is too much of a pita to get working and i highly doubt the average user (who cant even follow instructions properly) can even set it up, not to mention barely anyone with push access to the guide has almost no knowledge about how to fix issues with it

**Comment by upintheairsheep** [comment]
> i am absolutely not going to maintain a drc-sim guide. it is too much of a pita to get working and i highly doubt the average user (who cant even follow instructions properly) can even set it up, not to mention barely anyone with push access to the guide has almost no knowledge about how to fix issues with it

Just mention that tool or link its guide on the tutorial for people who do not have access to the gamepad.

**Comment by Lazr1026** [comment]
Vanilla is now a thing, and does what drc-sim (and drc-sim-e) did but 100x easier and simple
