### ISSUE TITLE
Safety Warning on Chrome

### ISSUE THREAD

**Issue by ErisuKuraku** [hacks-guide/Guide-WiiU#70]
when accessing the translation crowdin page, chrome blocks it claiming it might be a fake website and instead just asks you to go to hacks.guide instead.
![image](https://user-images.githubusercontent.com/25765196/95842827-ecfbf200-0d3e-11eb-8f32-9b690d7c028d.png)

**Comment by Elpunical** [comment]
Is it happening when using this url https://hacks-guide.crowdin.com/u/projects/10 ?

**Comment by ErisuKuraku** [comment]
yeah

**Comment by Elpunical** [comment]
Gary and I have tested it and we can’t reproduce this on Chrome for Windows it also doesn’t do this on Chrome for iOS.

**Comment by ErisuKuraku** [comment]
it's no longer doing it at all now, so thank you anyway and great job on the website.
